import Head from "next/head";
import Navbar from "../components/Navbar/Navbar";
import Footer from "../components/Footer/Footer";
import ScrollToTopButton from "../components/ScrollToTopButton/ScrollToTopButton";
import ButtonItem from "../components/Items/ButtonItem/ButtonItem";
import styles from "../styles/Home.module.sass";
import StartSection from "../components/StartSection/StartSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar></Navbar>

      <ScrollToTopButton></ScrollToTopButton>

      <main className={styles.main}>
        <StartSection />
        <section className={styles.itemsSection}>
          <ButtonItem />
          <ButtonItem />
          <ButtonItem />
        </section>
      </main>

      <Footer></Footer>
    </>
  );
}
